---
abstract: 'Validate German postal codes and map them to states'
author:
  - 'Jakob Voß'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PLZ
requires:
  Carp: 0
  Tree::Binary::Search: 1.0
  overload: 0
  strict: 0
  warnings: 0
version: 0.11
