---
abstract: 'Map German postal codes to German states'
author:
  - 'Jakob Voss <voss@gbv.de>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PLZ
requires:
  Carp: 0
  Tree::Binary::Search: 0
  overload: 0
version: 0.1
